// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUfjPB20ROy0ZqR-EjYQdUPRq2nQANe_s',
    appId: '1:219379898770:web:1da98438d78c77ebeec94b',
    messagingSenderId: '219379898770',
    projectId: 'chargepass-48fb9',
    authDomain: 'chargepass-48fb9.firebaseapp.com',
    storageBucket: 'chargepass-48fb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq6sWaHGOn01Hx8tZKPcevbfxy-tO0rJE',
    appId: '1:219379898770:android:332d15e8de4435a1eec94b',
    messagingSenderId: '219379898770',
    projectId: 'chargepass-48fb9',
    storageBucket: 'chargepass-48fb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJtt6W4k9L35vtoV1uJaEvlK3eJ6Wmq7Y',
    appId: '1:219379898770:ios:8de54c97d07536f9eec94b',
    messagingSenderId: '219379898770',
    projectId: 'chargepass-48fb9',
    storageBucket: 'chargepass-48fb9.firebasestorage.app',
    iosBundleId: 'com.example.chargepassv4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJtt6W4k9L35vtoV1uJaEvlK3eJ6Wmq7Y',
    appId: '1:219379898770:ios:8de54c97d07536f9eec94b',
    messagingSenderId: '219379898770',
    projectId: 'chargepass-48fb9',
    storageBucket: 'chargepass-48fb9.firebasestorage.app',
    iosBundleId: 'com.example.chargepassv4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUfjPB20ROy0ZqR-EjYQdUPRq2nQANe_s',
    appId: '1:219379898770:web:9d24c59ec44b2cd2eec94b',
    messagingSenderId: '219379898770',
    projectId: 'chargepass-48fb9',
    authDomain: 'chargepass-48fb9.firebaseapp.com',
    storageBucket: 'chargepass-48fb9.firebasestorage.app',
  );
}
