name: ChargePass Cost Analysis
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: "chargepass-${{ github.event.number || github.sha }}"
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.4"

      - name: Install Infracost CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          echo "$HOME/.infracost/bin" >> $GITHUB_PATH

      - name: Terraform Init
        working-directory: ./infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > chargepass-creds.json
          chmod 400 chargepass-creds.json
          terraform init -input=false

      - name: Terraform Plan
        working-directory: ./infra
        run: |
          terraform plan \
            -var="gcp_credentials=chargepass-creds.json" \
            -var="project_id=${{ secrets.PROJECT_ID || 'chargepass-dev' }}" \
            -out tfplan
          terraform show -json tfplan > plan.json

      - name: Run Infracost Analysis
        run: |
          infracost breakdown \
            --path ./infra/plan.json \
            --format table-html \
            --out-file infracost.html \
            --show-skipped

      - name: Upload Cost Report
        uses: actions/upload-artifact@v4
        with:
          name: chargepass-cost-report
          path: infracost.html

      - name: Post PR Comment (Infracost)
        if: github.event_name == 'pull_request'
        run: |
          infracost comment github \
            --path ./infra/plan.json \
            --repo $GITHUB_REPOSITORY \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --pull-request ${{ github.event.pull_request.number }} \
            --behavior update