name: ChargePass Cost Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  infracost:
    name: Infracost Analysis
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: "chargepass-${{ github.event.number || github.sha }}"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.4"

      - name: Setup Infracost
        uses: infracost/setup-action@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Terraform Init
        working-directory: ./infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > chargepass-creds.json
          terraform init -input=false

      - name: Terraform Plan
        working-directory: ./infra
        run: |
          terraform plan \
            -var="gcp_credentials=chargepass-creds.json" \
            -var="project_id=${{ secrets.PROJECT_ID || 'chargepass-dev' }}" \
            -out tfplan
          terraform show -json tfplan > plan.json

      - name: Run Infracost
        run: |
          infracost breakdown \
            --path ./infra/plan.json \
            --format table-html \
            --out-file infracost.html \
            --show-skipped

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: chargepass-cost-report
          path: infracost.html

      - name: Post Infracost Comment
        if: github.event_name == 'pull_request'
        uses: infracost/infracost-github-action@v0.1.0
        with:
          path: ./infra/plan.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          behavior: update